version: 2.1

parameters:
  trigger_build_app_image:
    type: boolean
    default: false
  app_name:
    type: string
    default: << pipeline.parameters.app_name >>

orbs:
  gcp-gcr: circleci/gcp-gcr@0.8.0

jobs:
  build_app_image:
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          docker-context: result
          path: << parameters.app >>
          image: voting/<< parameters.app >>
      - gcp-gcr/push-image:
          digest-path: /tmp/digest.txt
          image: voting/<< parameters.app >>

workflows:
  build_app_image:
    when: << pipeline.parameters.trigger_build_app_image >>
    jobs:
      - build_app_image

